  <%@taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>

 <!doctype html>
 <html lang="en">
 <head>
     <!-- Required meta tags -->
     <meta charset="utf-8">
     <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
                                              <!-- Bootstrap CSS -->

     <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
           integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

 </head>

 <body>

     <br><br>
 <h2 style="color:white">Olskers Cupcakes</h2>
 <p style="color:white">___________________________________________________________________</p>
 <h4 style="color:white">Our amazing cupcakes</h4>
 <p style="color:white">Something inspirational bla... bla...bla</p>
